# Generated by Django 4.2.20 on 2025-08-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Tomat, Cabai, Kangkung', max_length=100)),
                ('varietas', models.CharField(blank=True, help_text='Contoh: Cherry, Rawit, Bangkok', max_length=100)),
                ('lokasi_tanam', models.CharField(blank=True, help_text='Contoh: Pot A1, Polybag di teras', max_length=100)),
                ('tanggal_tanam', models.DateField()),
                ('catatan_kebutuhan', models.TextField(blank=True, help_text='Contoh: Butuh sinar matahari penuh, siram 2x sehari')),
                ('status_pertumbuhan', models.CharField(choices=[('Benih', 'Benih'), ('Berkecambah', 'Berkecambah'), ('Muda', 'Muda'), ('Dewasa', 'Dewasa'), ('Berbunga', 'Berbunga'), ('Berbuah', 'Berbuah'), ('Siap Panen', 'Siap Panen')], default='Benih', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Panen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_panen', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=2, help_text='Jumlah hasil panen (misal: dalam gram, kg, atau buah)', max_digits=10)),
                ('satuan', models.CharField(default='gram', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('tanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_panen', to='kebun.tanaman')),
            ],
            options={
                'ordering': ['-tanggal_panen'],
            },
        ),
        migrations.CreateModel(
            name='Masalah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_ditemukan', models.DateField()),
                ('deskripsi_masalah', models.TextField(help_text='Jelaskan hama, penyakit, atau masalah lain yang ditemukan')),
                ('solusi_dicoba', models.TextField(blank=True, help_text='Tindakan apa yang sudah dilakukan untuk mengatasi masalah')),
                ('berhasil', models.BooleanField(default=False)),
                ('tanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan_masalah', to='kebun.tanaman')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kegiatan', models.CharField(choices=[('Penyiraman', 'Penyiraman'), ('Pemupukan', 'Pemupukan'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('tanggal_jadwal', models.DateField()),
                ('selesai', models.BooleanField(default=False)),
                ('tanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_kegiatan', to='kebun.tanaman')),
            ],
            options={
                'ordering': ['tanggal_jadwal'],
            },
        ),
        migrations.CreateModel(
            name='CatatanPerawatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('aktivitas', models.TextField(help_text='Contoh: Menyiram, memberi pupuk NPK, menyemprot pestisida nabati')),
                ('foto_perkembangan', models.ImageField(blank=True, null=True, upload_to='foto_tanaman/')),
                ('tanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan_perawatan', to='kebun.tanaman')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
